apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  schemaVersion: v1.0.0
  name: kinesis-kafka-connector-location
  description: Links to additional entities in the kinesis-kafka-connector repository.
  annotations:
    github.com/project-slug: Bandwidth/kinesis-kafka-connector
spec:
  targets:
    - ./component.yaml
